### ISSUE TITLE
sugoiページの段階的表示機能

### ISSUE THREAD

**Issue by shirakurak** [shirakurak/sugoi#3]
本機能を組み込んだsugoiをsugoi 1.2とする

### 目的
本ページのアクセシビリティを向上する。
問題解決をもっと”かるく”行えるようにする（詳細にやるかはオプションとする）。

### TODO
 - [ ] 問題１のスペースを広げる（問題を言語化する段階では正確に書けないことが多い）
 - [ ] 簡易版ページと詳細版ページを分ける
 - [ ] 簡易ページ、詳細ページのデザイン・構成要素を整理した（決めた）資料を作成する
 - [ ] 簡易版がまず表示される　→　詳細版ページに遷移できる（ボタンの設置）
 - [ ] タイトル部分のデザインはどうするか？

### 簡易版
 - 問題1, 2, 4

### 注意
 - 現状のsugoiを包含する形であること
